
resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/nitram509/jbrotli.git
      branch: master

  - name: s3-jbrotli-releases
    type: s3
    source:
      bucket: {{s3-bucket-name}}
      regexp: jbrotli/releases/
      access_key_id: {{s3-access-key-id}}
      secret_access_key: {{s3-secret-access-key}}
      region_name: {{s3-region-name}}

jobs:
  - name: jbrotli
    plan:
    - get: git-repo
      trigger: true
    - task: maven-package-jbrotli-native-linux-x86-amd64
      privileged: false
      file: git-repo/pipeline-tasks/maven-package-jbrotli-native-linux-x86-amd64.yml
    - put: s3-jbrotli-releases
      params:
        file: target-linux-x86-amd64/*.tgz
    # - task: maven-package-jbrotli-native-linux-arm32-vfp-hflt
    #   privileged: false
    #   file: git-repo/pipeline-tasks/maven-package-jbrotli-native-linux-arm32-vfp-hflt.yml
